"""Name User

Revision ID: 274e1a71a9c9
Revises: 1d18594746f6
Create Date: 2025-10-10 13:54:47.554836

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "274e1a71a9c9"
down_revision: Union[str, Sequence[str], None] = "1d18594746f6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
