"""Init

Revision ID: ab90208f4d8d
Revises: 36ca321497f9
Create Date: 2025-09-19 16:05:32.840120

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "ab90208f4d8d"
down_revision: Union[str, Sequence[str], None] = "36ca321497f9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
