"""Fix User 2

Revision ID: 7a2043d0c836
Revises: 7e92ca76365f
Create Date: 2025-09-22 17:32:50.125021

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a2043d0c836'
down_revision: Union[str, Sequence[str], None] = '7e92ca76365f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('disabled', sa.Boolean(), nullable=False))
    op.create_index(op.f('ix_User_username'), 'User', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_User_username'), table_name='User')
    op.drop_column('User', 'disabled')
    # ### end Alembic commands ###
