"""Add user profile relationship

Revision ID: 1871cd2bc456
Revises: d6a0a7e0a74a
Create Date: 2025-10-06 17:25:26.695572

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1871cd2bc456'
down_revision: Union[str, Sequence[str], None] = 'd6a0a7e0a74a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
