"""Fix User

Revision ID: 03e21f8c7376
Revises: 7608cc15bcba
Create Date: 2025-09-19 16:38:02.875811

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "03e21f8c7376"
down_revision: Union[str, Sequence[str], None] = "7608cc15bcba"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("User", sa.Column("password", sa.String(length=32), nullable=False))
    op.drop_column("User", "surname")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("User", sa.Column("surname", sa.VARCHAR(length=32), nullable=False))
    op.drop_column("User", "password")
    # ### end Alembic commands ###
