"""Fix User 2

Revision ID: 7e92ca76365f
Revises: 03e21f8c7376
Create Date: 2025-09-22 17:10:19.953756

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "7e92ca76365f"
down_revision: Union[str, Sequence[str], None] = "03e21f8c7376"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
